### ISSUE TITLE
Tessera TLS SSLConfig with CA

### ISSUE THREAD

**Issue by tejasborawake8888** [Consensys-Incorporated/tessera#1318]
Hi Team,

We are trying to configure CA based TLS with Tessera on 2 node quorum setup.
We are having difficulty in communication between 2 TLS and are running into certificate related issues.
We are having hard time in certificate creation that satisfies SSL_CONFIG part on config_json.
We are getting these 2 errors:

Failed to connect to node https://172.31.6.147:9001/, due to javax.net.ssl.SSLHandshakeException: No subject alternative names(SAN) present

Failed to connect to node https://172.31.6.147:9001/, due to javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Do you have any documentation of working example showing how to handle CA based TLS config for Tessera apart from 
standard documentation of Tessera?
We are finding it hard to get any example of working CA based TLS for Tessera online. Could you please help us in getting these configuration?

I am attaching certificates and config.json and san.conf i have used to create self-signed certificates for your reference.

[Node1 Certificates-San-config_json.zip](https://github.com/ConsenSys/tessera/files/6848461/Node1.Certificates-San-config_json.zip)
[Node4-certificates-config_json-san_conf.zip](https://github.com/ConsenSys/tessera/files/6848469/Node4-certificates-config_json-san_conf.zip)

**Comment by macfarla** [comment]
Regarding the `No SAN present` error, this could be because your cert is generated with something like 127.0.0.1:8080 in the CN field of the certificate. When it comes to IP address Java is stricter that it enforces the certificate contains a SAN (Subject Alternative Names) entry for the IP as having the url in the CN has become obsolete.

We have some instructions in the Orion docs on how to generate certs, using OpenSSL, that fulfil this requirement.
* Either Follow the instruction here https://docs.orion.consensys.net/en/stable/Tutorials/Generating-Certificates/#public-dns-is-cn and ensure that the CN=localhost
* OR Follow instruction here https://docs.orion.consensys.net/en/stable/Tutorials/Generating-Certificates/#ip-address-is-cn and have the SAN configured to include 127.0.0.1 and Tessera should be able to start with those certificates

**Comment by macfarla** [comment]
Hi @tejasborawake8888 closing this as per slack thread :)
> Thanks a lot we got the issue resolved. it wasnt certificate issue. we had missed adding DNS in etc/hosts file bcos of which it wasn't recognising the certificates
