### ISSUE TITLE
TLS mode "CA" not working

### ISSUE THREAD

**Issue by Himanshu-Pandey** [Consensys-Incorporated/tessera#563]
I am using sslConfig provided in the wiki : https://github.com/jpmorganchase/tessera/wiki/TLS .
It did not worked.

Getting issue: 
`2018-12-05 10:09:47,920 DEBG 'tessera' stdout output:
Config validation issue: serverConfig.sslConfig Trust store config not valid. If server trust mode is CA, trust store must exist and not be null
`

**Comment by prd-fox** [comment]
The Wiki suggests that Tessera can generate CA stores if they don't exist with the following property:
```
"generateKeyStoreIfNotExisted" : "true"
```

Is this what you are doing?

With a CA the stores must be provided beforehand that is signed by the CA, else it will be self signed which isn't what you want when using the CA option.

**Comment by Himanshu-Pandey** [comment]
then what does the "generateKeyStoreIfNotExisted" flag do?

**Comment by namtruong** [comment]
`generateKeyStoreIfNotExisted` being set to `true` will automatically generate the keystore files for the node (self-signed), but not the trust store. This will work with trust modes such as TOFU, because it uses a `knownClientsFile` or `knownServersFile ` for the list of trusted certificates.

To use CA mode, you need to specify the trust store (which probably will be the CA that signed the certificates)

**Comment by namtruong** [comment]
Will close this as not an issue - the message observed 
`2018-12-05 10:09:47,920 DEBG 'tessera' stdout output: Config validation issue: serverConfig.sslConfig Trust store config not valid. If server trust mode is CA, trust store must exist and not be null`
 is a valid config validation message.

If you wish to use CA trust mode, on the same wiki page 
https://github.com/jpmorganchase/tessera/wiki/TLS, please scroll down to the CA Trust mode section for the relevant sample config

**Comment by Himanshu-Pandey** [comment]
Thanks for your help!!
