### ISSUE TITLE
javax.xml.bind.DataBindingException on config-migration

### ISSUE THREAD

**Issue by dhyansraj** [Consensys-Incorporated/tessera#626]
I am trying to implement 0.8 support in QM. Was getting duplicate field errors due to HashicorpKeyVaultConfig and after adding, @XmlAccessorType(XmlAccessType.FIELD) at class level the exception is changed to javax.xml.bind.DataBindingException: javax.xml.bind.PropertyException: eclipselink.beanvalidation.mode. I get same error on master branch as well without any modification. 

What am I doing wrong?

**Comment by melowe** [comment]
Hi 

What java version or you using?

**Comment by dhyansraj** [comment]
OpenJDK 8

**Comment by melowe** [comment]
That is strange. 

If you can if you can provide us us with the startup arts you’re using and your config we’ll try and replicate.

**Comment by chris-j-h** [comment]
Hi,

There was an issue with the JAXB marshaller setup in the config migration utility causing this issue.  #627 resolves this and is now included in master.  

For Tessera 0.8 the issue can be fixed by setting the following properties when using config migration: `-Djavax.xml.bind.JAXBContextFactory=org.eclipse.persistence.jaxb.JAXBContextFactory -Djavax.xml.bind.context.factory=org.eclipse.persistence.jaxb.JAXBContextFactory` 

For example:
```
java -Djavax.xml.bind.JAXBContextFactory=org.eclipse.persistence.jaxb.JAXBContextFactory -Djavax.xml.bind.context.factory=org.eclipse.persistence.jaxb.JAXBContextFactory \
     -jar /path/to/config-migration-0.8-cli.jar \
     --tomlfile="/path/to/legacy.toml" 
```
