### ISSUE TITLE
NullPointerException on /upcheck with unix socket Q2T server

### ISSUE THREAD

**Issue by vdamle** [Consensys-Incorporated/tessera#811]
Tessera Version: 0.9.2+ (latest on master)
Quorum version: 2.2.3

Using the latest code on master, I have Tessera running with Q2T server bound to a unix socket:

```
    {
      "app": "Q2T",
      "enabled": true,
      "serverAddress": "unix:///<path>/constellation.ipc",
      "communicationType": "REST"
    }
```

Logs suggest that the unix socket was opened fine. However, a call to `/upcheck` by sending the string specified here: https://github.com/jpmorganchase/quorum/blob/v2.2.3/core/private_state_test.go#L242 returns with a `500` error. Attached the error log in Tessera with a few relevant lines before it. Given this is a unix socket, not sure if expecting a hostname/port is correct. Attempting a few workarounds, will update here if anything clicks.

[npe.log](https://github.com/jpmorganchase/tessera/files/3348296/npe.log)

**Comment by prd-fox** [comment]
The configuration looks good. The error is certainly odd, since it comes from the underlying library that handles the socket. Indeed a hostname/port isn't needed, but the library should be handling that.

I haven't yet been able to reproduce this issue, here are some of things I've tried:

1. `printf 'GET /upcheck HTTP/1.0\r\n\r\n' | nc -Uv qdata/c1/tm.ipc | tail -n 1`
2. `curl --unix qdata/c1/tm.ipc http://localhost/upcheck`

The test you linked has some oddities which I'm not sure are valid, but the string that is contained there should be fine, and in fact I used it for point 1.

Was this a one time issue or does it happen with predictability?

**Comment by vdamle** [comment]
This error is consistent for me. The check never returns a success, I poll that URL before starting quorum, as a way to determine that Tessera is ready.

**Comment by prd-fox** [comment]
Do both of the commands above give the error?

As I mentioned, so far I am unable to reproduce this.

Are you able to share your full configuration and which OS you are using?

**Comment by vdamle** [comment]
Thanks, @prd-fox . The 2nd URL works for me. Running Tessera on a Linux OS running in docker/kubernetes. I have changed the way we check the `/upcheck` endpoint and quorum starts fine now as well.
